import type { FishSpecies } from './species';

/** Semente mínima e REGIONALIZADA do catálogo (curadoria completa depois — D-11). */
export const SPECIES_SEED: readonly FishSpecies[] = [
  {
    id: 'tucunare-acu',
    namePt: 'Tucunaré-açu',
    nameEs: 'Tucunaré',
    nameEn: 'Speckled peacock bass',
    scientificName: 'Cichla temensis',
    habitat: 'freshwater',
    rarity: 'rare',
    regions: ['BR'],
    maxPlausibleSizeCm: 100,
    maxPlausibleWeightKg: 14,
  },
  {
    id: 'dourado',
    namePt: 'Dourado',
    nameEs: 'Dorado',
    nameEn: 'Golden dorado',
    scientificName: 'Salminus brasiliensis',
    habitat: 'freshwater',
    rarity: 'uncommon',
    regions: ['BR', 'AR'],
    maxPlausibleSizeCm: 100,
    maxPlausibleWeightKg: 30,
  },
  {
    id: 'tilapia',
    namePt: 'Tilápia',
    nameEs: 'Tilapia',
    nameEn: 'Nile tilapia',
    scientificName: 'Oreochromis niloticus',
    habitat: 'freshwater',
    rarity: 'common',
    regions: ['BR', 'US'],
    maxPlausibleSizeCm: 60,
    maxPlausibleWeightKg: 5,
  },
  {
    id: 'black-bass',
    namePt: 'Black bass',
    nameEs: 'Lobina negra',
    nameEn: 'Largemouth bass',
    scientificName: 'Micropterus salmoides',
    habitat: 'freshwater',
    rarity: 'uncommon',
    regions: ['US', 'BR'],
    maxPlausibleSizeCm: 75,
    maxPlausibleWeightKg: 10,
  },
  {
    id: 'robalo',
    namePt: 'Robalo',
    nameEs: 'Róbalo',
    nameEn: 'Common snook',
    scientificName: 'Centropomus undecimalis',
    habitat: 'saltwater',
    rarity: 'uncommon',
    regions: ['BR', 'US'],
    maxPlausibleSizeCm: 140,
    maxPlausibleWeightKg: 25,
  },
  {
    id: 'dourado-do-mar',
    namePt: 'Dourado-do-mar',
    nameEs: 'Dorado de mar',
    nameEn: 'Mahi-mahi',
    scientificName: 'Coryphaena hippurus',
    habitat: 'saltwater',
    rarity: 'rare',
    regions: ['BR', 'US', 'AR'],
    maxPlausibleSizeCm: 210,
    maxPlausibleWeightKg: 40,
  },
];
